.TH "DLMODEL2DEB" "1" "October 2017" "DLMobelBox" "User Commands"

.SH NAME
dlmodel2deb \- create a deep learning model package from a structured model directory

.SH SYNOPSIS
.B dlmodel2deb <model_dirpath>

.SH DESCRIPTION
.PP
.B dlmodel2deb
creates a deep learning (DL) model package from a structured model directory.
.PP
To create a structured model directory, please refer to the
.B dlmodel_source
command.

.SH SEE ALSO
.PP
.BR dlmodel_source (1)
